import type {Config} from '@docusaurus/types';
import fs from 'fs';
import path from 'path';

// 🌌 Workspace Discovery
// We automatically detect any workspaces checked into Git or generated by sync script.
const dynamicDocsPlugins: any[] = [];
const dynamicDocsPath = path.join(__dirname, 'workspaces');

if (fs.existsSync(dynamicDocsPath)) {
  const slugs = fs.readdirSync(dynamicDocsPath);
  slugs.forEach(slug => {
    // Only process directories
    const fullPath = path.join(dynamicDocsPath, slug);
    if (fs.statSync(fullPath).isDirectory()) {
      // Docusaurus fails if a plugin has no documents.
      // We check if at least one .md file exists in the directory.
      const hasDocs = fs.readdirSync(fullPath).some(file => file.endsWith('.md'));
      
      if (hasDocs) {
        dynamicDocsPlugins.push([
          '@docusaurus/plugin-content-docs',
          {
            id: slug,
            path: `workspaces/${slug}`,
            routeBasePath: `workspace/${slug}`,
            sidebarPath: `./sidebars-${slug}.json`,
          }
        ]);
      } else {
        console.warn(`[Docusaurus] Skipping workspace "${slug}" because it contains no documents.`);
      }
    }
  });
}

const config: Config = {
  title: 'Delta Labs Documentation',
  tagline: 'Everything you need to build with Delta Labs',
  url: 'https://delta-labs-docs-cyan.vercel.app',
  baseUrl: '/',
  onBrokenLinks: 'warn',
  markdown: {
    format: 'md',
    mermaid: true,
    preprocessor: ({filePath, fileContent}) => {
      return fileContent;
    },
    onBrokenMarkdownLinks: 'warn',
    mdx1Compat: {
      comments: true,
      admonitions: true,
      headingIds: true,
    },
  },
  organizationName: 'Dink',
  projectName: 'delta-labs-docs',

  customFields: {
    apiUrl: process.env.REACT_APP_API_URL || 'https://delta-labs-backend.onrender.com',
  },

  staticDirectories: ['static'],

  presets: [['classic', {
    docs: {
      sidebarPath: './sidebars.ts',
      routeBasePath: '/',  // Main 'docs' workspace appears at root URL
    },
    blog: false,
    theme: { customCss: './src/css/custom.css' },
  }]],

  plugins: [
    ...dynamicDocsPlugins, // Inject dynamic workspace plugins
  ],

  themeConfig: {
    navbar: {
      title: 'Delta Labs Docs',
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Documentation',
        },
        {
          type: 'custom-WorkspaceSwitcher',
          position: 'left',
        },
        {
          // Logout — clears JWT from localStorage and reloads (AuthGuard shows login form)
          type: 'html',
          position: 'right',
          value: `<button
            onclick="localStorage.removeItem('delta_token'); window.location.reload();"
            style="
              background: transparent;
              color: var(--ifm-color-primary);
              border: 1.5px solid var(--ifm-color-primary);
              padding: 5px 14px;
              border-radius: 6px;
              cursor: pointer;
              font-size: 13px;
              font-weight: 600;
              transition: background 0.15s, color 0.15s;
            "
            onmouseover="this.style.background='var(--ifm-color-primary)'; this.style.color='white';"
            onmouseout="this.style.background='transparent'; this.style.color='var(--ifm-color-primary)';"
          >Logout</button>`,
        },
      ],
    },
  },
};

export default config;

